<?php

namespace GL\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlmaArrayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlmaArrayRepository extends EntityRepository
{
}
