<?php

namespace GL\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SequenceStepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SequenceStepRepository extends EntityRepository
{
}
